version: '2'

volumes:
  logs:
    driver: local

services:
  api-db:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_USER=apidev
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=api_core
    ports:
      - "2354:5432"