version: '2'

volumes:
  logs:
    driver: local

services:
  slim:
    image: php:7.1-alpine
    working_dir: /var/www
    command: php -S 0.0.0.0:8080 -t web index.php
    environment:
      docker: "true"
    ports:
      - 8080:8080
    volumes:
      - .:/var/www
      - /resource/logs:/var/www/resource/logs